# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/demo/imu"
  gz_topic_name: "/demo/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

# Cameras
- ros_topic_name: "/front_left/image_raw"
  gz_topic_name: "/front_left/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/bottom/image_raw"
  gz_topic_name: "/bottom/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Ground Truth Odometry
- ros_topic_name: "/ground_truth/odom"
  gz_topic_name: "/model/varuna/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/varuna/pose"
  gz_topic_name: "/model/varuna/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

# Thruster Commands
- ros_topic_name: "/thruster1_cmd"
  gz_topic_name: "/model/varuna/joint/front_right_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster2_cmd"
  gz_topic_name: "/model/varuna/joint/front_left_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster3_cmd"
  gz_topic_name: "/model/varuna/joint/back_right_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster4_cmd"
  gz_topic_name: "/model/varuna/joint/back_left_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster5_cmd"
  gz_topic_name: "/model/varuna/joint/surge_right_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster6_cmd"
  gz_topic_name: "/model/varuna/joint/surge_left_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster7_cmd"
  gz_topic_name: "/model/varuna/joint/sway_thrust_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/thruster8_cmd"
  gz_topic_name: "/model/varuna/joint/sway_back_joint/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ